### ISSUE TITLE
Pesquisa e Definição do Perfil dos Usuários

### ISSUE THREAD

**Issue by Marcelo-Adrian** [Interacao-Humano-Computador/2024.2-CDMOJ#12]
Descrição:
Realizar pesquisas para compreender o perfil dos usuários do sistema, considerando atributos, grupos de atributos e os aspectos necessários para análise.

Tarefas:
- [x] Elaborar o planejamento da pesquisa para identificar o perfil dos usuários.
- [x] Levantar dados demográficos e comportamentais, incluindo idade, sexo, status socioeconômico, experiências profissionais, educação e informações sobre as empresas dos usuários.
- [x] Identificar e descrever grupos de atributos com base no Capítulo 8 (Hackos e Redish, 1998; Courage e Baxter, 2005):
- [x] Idade (criança, jovem, adulto, idoso).
- [x] Experiência (leigo, especialista).
- [x] Atitudes (tecnófilos, tecnófobos).
- [x] Tarefas primárias (compra, venda, etc.).
- [x] Criar personas baseadas nos dados coletados, com referência bibliográfica e imagens dos textos utilizados.

Critérios de Aceitação:
- [ ] O perfil do usuário inclui atributos detalhados (demográficos, profissionais, educacionais).
- [ ] Os grupos de atributos são definidos e baseados em fontes confiáveis, com evidências documentadas.
- [ ] As personas representam adequadamente os diferentes tipos de usuários.
- [ ] Referências bibliográficas e imagens das fontes utilizadas estão anexadas.

**Comment by xzxjesse** [comment]
Responsáveis: João Vitor, Felipe Rodrigues
Revisor: Jéssica Eveline
