### ISSUE TITLE
Aspectos Éticos e Termo de Consentimento

### ISSUE THREAD

**Issue by Marcelo-Adrian** [Interacao-Humano-Computador/2024.2-CDMOJ#13]
Descrição:
Definir os aspectos éticos para pesquisas envolvendo pessoas, assegurando conformidade com os princípios éticos e privacidade dos participantes.

Tarefas:
- [x] Descrever os princípios éticos utilizados:
- [x] Autonomia.
- [x] Beneficência.
- [x] Não maleficência.
- [x] Justiça e equidade.
- [x] Criar o Termo de Consentimento Livre e Esclarecido (TCLE) dos participantes, incluindo permissão para gravações de voz e imagem.
- [x] Anexar referências bibliográficas e imagens dos textos que explicam os aspectos éticos e o TCLE.

Critérios de Aceitação:
- [x] Os princípios éticos estão claramente definidos e descritos.
- [x] O TCLE foi elaborado e está adequado às diretrizes do projeto.
- [x] Referências bibliográficas e imagens das fontes estão anexadas e completas.

**Comment by xzxjesse** [comment]
Responsáveis: Jéssica Eveline, Marcelo Adrian
Revisor: Ruan Carvalho
