### ISSUE TITLE
Cenários e Análise de Tarefas

### ISSUE THREAD

**Issue by Marcelo-Adrian** [Interacao-Humano-Computador/2024.2-CDMOJ#15]
Descrição:
Criar cenários para validar as interações dos usuários com o sistema e realizar análise de tarefas para especificar atividades realizadas pelos usuários.

Tarefas:
- [ ] Elaborar cenários que detalhem interações reais dos usuários.
- [ ] Realizar análise de tarefas com pelo menos duas técnicas, como HTA e GOMS.
- [ ] Documentar e justificar a escolha das técnicas utilizadas.
- [ ] Adicionar referências bibliográficas.
- [ ] Adcionar artefatos ao mkdocs.

Critérios de Aceitação:
- [ ] Os cenários estão completos e descrevem interações relevantes.
- [ ] A análise de tarefas utiliza ao menos duas técnicas e está documentada.
- [ ] Artefatos acessiveis pelo Pages.

**Comment by xzxjesse** [comment]
Responsáveis: Felipe Rodrigues, Jéssica Eveline, João Vitor, Ruan Carvalho, Marcelo Adrian
Revisores: Felipe Rodrigues, Jéssica Eveline, João Vitor, Ruan Carvalho, Marcelo Adrian
