### ISSUE TITLE
Revisão e Organização do Documento

### ISSUE THREAD

**Issue by Marcelo-Adrian** [Interacao-Humano-Computador/2024.2-CDMOJ#3]
#### **Tarefas:**  
- [x] Disponibilizar o link para o Heatmap do projeto.  
- [x] Ordenar a tabela de ferramentas em ordem alfabética.  
- [ ] Incluir o termo de uso do site escolhido no documento.  

#### **Critérios de Aceitação:**  
- [x] O link para o Heatmap deve estar acessível e funcionando.  
- [x] A tabela de ferramentas deve estar ordenada alfabeticamente e formatada corretamente.  
- [ ] O termo de uso do site escolhido deve ser incluído no documento para fins de preservação.

**Comment by xzxjesse** [comment]
O site escolhido não contém termos de uso.
